config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :categories
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  has_one_attached :preview_img
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy

    scope :ordered, -> { order(:title) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = categories_collection
  end

  # GET /articles/1/edit
  def edit
    @categories = categories_collection
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :category_id, :preview_img)
    end

    def categories_collection
      Category.ordered.pluck(:title, :id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: "Category was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = articles_collection
    p @articles.last.preview_img
  end

  private

  def articles_collection
    Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= article.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= article.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= article.category_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this article", article, class: "rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
    <%= link_to 'Edit this article', edit_article_path(article), class: "rounded-lg py-3 ml-2 px-5 bg-black inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border text-black border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_field :body, class: "block shadow rounded-md border text-black border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories, class: "block shadow rounded-md border border-gray-200 text-black outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.label :preview_img %>
    <%= form.file_field :preview_img, class: "block shadow rounded-md border text-black border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-black inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <%= link_to 'New article', new_article_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-black block font-medium" %>
  </div>

  <div id="articles" class="min-w-full">
    <%= render @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to 'Back to articles', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <%= link_to 'Edit this article', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this article', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-black font-medium" %>
    </div>
    <%= link_to 'Back to articles', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
  </div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= category.title %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
    <%= link_to 'Edit this category', edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-black inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 ">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full text-black" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-black inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-black block font-medium" %>
  </div>

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to 'Edit this category', edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this category', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-black font-medium" %>
    </div>
    <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-black inline-block font-medium" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-black text-black">
  <div class="px-32 py-16 mx-auto">
    <div class="flex justify-between items-center">
      <p class="text-2xl font-bold">QWERy</p>

      <div class="flex items-baseline">
        <p class="mb-2 mr-5">Ready to explore?</p>
        <%= link_to "Get Started", "javascript:void(0)", class: "btn-orange" %>
      </div>
    </div>

    <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

    <div class="flex justify-between mr-5">
      <div>
        <p class="max-w-xs text-xl font-semibold">
          Let's go on vacation,
        </p>
        <p class="max-w-xs text-xl font-semibold">
          Make your day
        </p>

        <div class="flex mt-8 space-x-6 text-gray-600">
          <%= form_with url: "/send_mail", method: :get do |form| %>
            <%= form.text_field :query, placeholder: "Email address", id: "contact-input", class: "bg-transparent" %>

            <%= form.submit "", id: "contact-submit" %>
          <% end %>
        </div>
      </div>

      <div>
        <p class="font-medium orange-text font-semibold">
          Services
        </p>
        <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-300">
          <%= link_to "Email marketing", "javascript:void(0)" %>
          <%= link_to "Campaigns", "javascript:void(0)" %>
          <%= link_to "Branding", "javascript:void(0)" %>
          <%= link_to "Offline", "javascript:void(0)" %>
        </nav>
      </div>

      <div>
        <p class="font-medium orange-text font-semibold">
          About
        </p>
        <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-300">
          <%= link_to "Our Story", "javascript:void(0)" %>
          <%= link_to "Benefits", "javascript:void(0)" %>
          <%= link_to "Team", "javascript:void(0)" %>
          <%= link_to "Careers", "javascript:void(0)" %>
        </nav>
      </div>

      <div>
        <p class="font-medium orange-text font-semibold">
          Help
        </p>
        <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-300">
          <%= link_to "FAQs", "javascript:void(0)" %>
          <%= link_to "Contact Us", "javascript:void(0)" %>
        </nav>
      </div>

    </div>

    <div class="flex justify-between items-center mt-12">
      <div>
        <%= link_to "Terms & Conditions", "javascript:void(0)", class: "mx-5 text-xs" %>
        <%= link_to "Privacy Policy", "javascript:void(0)", class: "mx-5 text-xs" %>
      </div>

      <div class="flex items-baseline">
        <%= button_to "https://www.facebook.com/" , class: "text-black mx-3" do %>
          <i class="fa-brands fa-facebook-f text-white"></i>
        <% end %>

        <%= button_to "https://twitter.com/" , class: "text-black mx-3" do %>
          <i class="fa-brands fa-twitter text-white"></i>
        <% end %>

        <%= button_to "https://www.instagram.com/" , class: "text-black mx-3" do %>
          <i class="fa-brands fa-instagram text-white"></i>
        <% end %>
      </div>
    </div>
    <p class="mt-8 text-xs font-semibold text-gray-500 text-center">
      Copyright <%= Date.current.year %> QWERy
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="w-full text-gray-700 body-font">
  <div class="px-16 flex flex-col items-start justify-between p-6 mx-auto md:flex-row">
    <%= link_to "QWERy", root_path, class: "flex items-center mb-4 font-medium title-font md:mb-0" %>

    <nav class="flex flex-wrap items-center justify-center pl-24 text-base md:ml-auto md:mr-auto">
      <%= link_to "Information", "javascript:void(0)", class: "mr-5 font-medium" %>
      <%= link_to "About us", "javascript:void(0)", class: "mr-5 font-medium" %>
      <%= link_to "Culture", "javascript:void(0)", class: "mr-5 font-medium" %>
    </nav>

    <div class="items-center h-full">
    
      <%= link_to "javascript:void(0)", class: "mr-5 font-medium " do %>
        <i class="fa fa-thin fa-magnifying-glass inline mr-2"></i>
        <p class="mr-5 font-medium inline ">Search</p>
       <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-element-bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/cba15fe931.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="block">
  <div class="flex justify-center"  id="start-page">
      <div class="flex rotate-90 social-links">
        <p class="mx-3">Follow us</p>

        <%= button_to "https://www.instagram.com/", class: "mx-3" do %>
          <i class="fa-brands fa-instagram -rotate-90"></i>
        <% end %>

        <%= button_to "https://twitter.com/" , class: "mx-3" do %>
          <i class="fa-brands fa-twitter -rotate-90"></i>
        <% end %>

        <%= button_to "https://www.facebook.com/" , class: "mx-3" do %>
          <i class="fa-brands fa-facebook-f -rotate-90"></i>
        <% end %>

      </div>
    <div class="w-2/5">
      <div class="flex items-center">
        <hr class="w-16 h-1 my-8 mr-5 border-0 rounded custom-orange-dash">
        <p class="custom-orange uppercase text-sm font-bold tracking-widest">Explore the nature beauty</p>
      </div>

      <div class="mb-5">
        <p class="text-6xl font-bold mb-2">Discover</p>
        <p class="text-5xl">Wonderful Indonesia</p>
      </div>
    </div>

    <div class="flex justify-center mt-5 pt-5 items-end" id="scrolling-hint">
      <p class="mr-3 mt-5 pt-5">Scroll Down<p>
      <i class="fa fa-light fa-arrow-down mt-5 pt-5"></i>
    </div>

  </div>



  <div class="block my-5">
    <div class="flex justify-center">
      <div class="flex justify-between items-center w-3/4">

        <%= image_tag @articles.first.preview_img, class: "article-preview w-2/5" %>

        <div class="block w-1/2">
          <div class="flex items-center">
            <hr class="w-16 h-1 my-8 mr-5 border-0 rounded custom-orange-dash">
            <p class="custom-orange uppercase text-sm font-bold tracking-widest"><%= @articles.first.category.title %></p>
          </div>

          <p class="text-5xl font-bold mb-5"><%= @articles.first.title %></p>
          <p class="mb-5"><%= @articles.first.body %></p>

          <%= link_to "read more", "javascript:void(0)", class: "inline mt-5 custom-orange" %>
          <i class="fa-solid fa-arrow-right custom-orange"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="block my-5">
    <div class='flex justify-center'>
      <div class="block w-3/4">
        <swiper-container navigation="true" pagination="true" scrollbar="true" effect="coverflow">
          <% @articles.each do |article| %>
            <swiper-slide>
              <%= image_tag article.preview_img, class: "slide-img" %>

              <div class=" flex article-slide-info">
                <div class="flex align-baseline">
                  <hr class="w-16 h-1 my-8 mr-5 border-0 rounded custom-orange-dash">
                  <p class="flex items-center custom-orange uppercase text-sm font-bold tracking-widest"><%= article.category.title %></p>
                  <hr class="w-16 h-1 my-8 ml-5 border-0 rounded custom-orange-dash">
                </div>

                <p class="text-6xl font-bold mb-5"><%= article.title %></p>
                <p class="mb-5"><%= article.body %></p>

                <div class="inline">
                  <%= link_to "read more", "javascript:void(0)", class: "inline mt-5 custom-orange" %>
                  <i class="inline-flex fa-solid fa-arrow-right custom-orange"></i>
                </div>

              </div>
            </swiper-slide>
          <% end %>
        </swiper-container>
      </div>
    </div>
  </div>

    <div class="block my-5">
    <div class="flex justify-center">
      <div class="flex justify-between items-center w-3/4">

        <div class="block w-1/2">
          <div class="flex items-center">
            <hr class="w-16 h-1 my-8 mr-5 border-0 rounded custom-orange-dash">
            <p class="custom-orange uppercase text-sm font-bold tracking-widest"><%= @articles.last.category.title %></p>
          </div>

          <p class="text-5xl font-bold mb-5"><%= @articles.last.title %></p>
          <p class="mb-5"><%= @articles.last.body %></p>

          <%= link_to "read more", "javascript:void(0)", class: "inline mt-5 custom-orange" %>
          <i class="fa-solid fa-arrow-right custom-orange"></i>
        </div>

        <%= image_tag @articles.last.preview_img, class: "article-preview w-2/5" %>
      </div>
    </div>
  </div>







</div>